version: "3.7"
# =======================
services:
  # web server
  web:
    container_name: web
    image: nginx:1.18
    ports:
      - "8080:80"
    volumes:
      - ./code:/var/www/html
      - ./docker-file/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network
    depends_on:
      - php
  # php
  php:
    container_name: php
    build:
      context: docker-file
      dockerfile: Dockerfile
    volumes:
      - ./code:/var/www/html
    networks:
      - network
    depends_on:
      - db
  # database
  db:
    container_name: db
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
    - '33061:3306'
    networks:
      - network
# =======================
volumes:
  db_data:

networks:
  network:
    driver: bridge